# Generated by Django 3.2.13 on 2022-04-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeI4Aggregation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='componentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=122)),
                ('DrawingNo', models.CharField(max_length=122)),
                ('qpp', models.CharField(max_length=122)),
                ('Level', models.CharField(max_length=122)),
                ('description', models.CharField(default=0, max_length=122)),
                ('modelName', models.CharField(default=0, max_length=122)),
                ('currentDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HMIDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operatorname', models.CharField(max_length=122)),
                ('identity', models.CharField(max_length=122)),
                ('machine', models.CharField(max_length=122)),
                ('variant', models.CharField(max_length=122)),
                ('partname', models.CharField(max_length=122)),
                ('partno', models.CharField(max_length=122)),
                ('timein', models.DateTimeField(null=True)),
                ('timeout', models.DateTimeField(null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='inhouseInventory',
            fields=[
                ('sno', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('productSno', models.CharField(default=0, max_length=122)),
                ('level', models.CharField(default=0, max_length=122)),
                ('qpp', models.CharField(default=0, max_length=122)),
                ('dimension', models.CharField(default=0, max_length=122)),
                ('drawingno', models.CharField(default=0, max_length=122)),
                ('availableNos', models.CharField(default=0, max_length=122)),
                ('description', models.CharField(default=0, max_length=122)),
                ('timein', models.DateTimeField(null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='machineDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=122)),
                ('Manufacturer', models.CharField(max_length=122)),
                ('shopName', models.CharField(max_length=122)),
                ('MachineNo', models.CharField(max_length=122)),
                ('Description', models.CharField(default=0, max_length=122)),
                ('remarks', models.CharField(default=0, max_length=122)),
                ('currentDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='operationsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operationName', models.CharField(max_length=300)),
                ('inputComponentsName', models.CharField(max_length=300)),
                ('outputComponentsName', models.CharField(max_length=300)),
                ('operationMachineName', models.CharField(max_length=300)),
                ('operationTime', models.CharField(max_length=300)),
            ],
        ),
    ]
