# Generated by Django 3.2.13 on 2022-04-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeI4Aggregation', '0003_auto_20220426_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='makelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=122)),
                ('machineName', models.CharField(max_length=122)),
                ('startTime', models.CharField(max_length=122)),
                ('EndTime', models.CharField(max_length=122)),
                ('operationName', models.CharField(default=0, max_length=122)),
            ],
        ),
    ]
