# Generated by Django 3.2.13 on 2022-05-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeI4Aggregation', '0005_auto_20220502_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryIN',
            fields=[
                ('sno', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('productSno', models.CharField(default=0, max_length=122)),
                ('level', models.CharField(default=0, max_length=122)),
                ('qpp', models.CharField(default=0, max_length=122)),
                ('drawingno', models.CharField(default=0, max_length=122)),
                ('availableNos', models.CharField(default=0, max_length=122)),
                ('timein', models.DateTimeField(null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
